"""Apple Reminders via Apple Shortcuts — pure string helpers.

Framework-agnostic and offline: task data in, strings out. No network, no
auth, no secrets. The functions here help a project drive Apple's Shortcuts
app to create a **Reminders** task, and detect whether the current visitor is
on an Apple platform (so the button can be surfaced appropriately).

Mechanics (out of scope for this library, but useful to understand the API):

1. **One-time setup (first run).** The user installs one Shortcut that reads
   its dictionary *input* and adds a Reminder. Two install sources exist:

   * **(A) built-in unsigned ``.shortcut``** — generated by this library via
     :func:`build_reminder_shortcut` / :func:`write_reminder_shortcut`. Fully
     self-contained (no external hosting), but on the device it requires
     "Allow Untrusted Shortcuts" plus one manual run to grant Reminders
     access. **Honest limit:** an Apple-*signed* iCloud link cannot be minted
     from code — signing happens on Apple's side.
   * **(B) signed iCloud share link** — published once by a human
     (``https://www.icloud.com/shortcuts/...``); frictionless for users and
     the recommended production path. The library does not (cannot) generate
     it; you pass it in as configuration.

   :func:`reminder_setup_instructions` / :func:`reminder_setup_html` render the
   first-run onboarding for *either* source.
2. **Per-task launch.** For each task the project builds a
   ``shortcuts://run-shortcut?name=...&input=<JSON>`` URL with
   :func:`shortcuts_reminder_url` and opens it on the Apple device; the
   Shortcut receives the JSON as input and creates the Reminder.

The JSON payload uses a **fixed set of keys** so the Shortcut can be built
against a stable contract:

    title  (str)        -- reminder title
    due    (str|None)   -- ISO-8601 due date/time (with offset if tz-aware)
    notes  (str|None)   -- free-text notes
    url    (str|None)   -- associated link

Extra keys may be merged in via ``shortcut_input_extra``.

Public API:
    shortcuts_reminder_url(...)     -> str    # shortcuts:// launch URL
    detect_apple(user_agent)        -> AppleDevice
    reminder_entry_mode(ua)         -> str    # "apple" | "unknown"
    reminder_landing_html(...)      -> str    # per-task landing page
    build_reminder_shortcut(...)    -> bytes  # unsigned .shortcut plist
    write_reminder_shortcut(...)    -> None   # write that plist to a file
    reminder_setup_instructions(...) -> list  # ordered first-run steps
    reminder_setup_html(...)        -> str    # first-run setup page
"""

from __future__ import annotations

import datetime as _dt
import json as _json
import os as _os
import plistlib as _plistlib
from dataclasses import dataclass
from html import escape as _escape
from typing import Any, Mapping, Optional, Sequence, Union
from urllib.parse import quote
from uuid import uuid4 as _uuid4
from zoneinfo import ZoneInfo

__all__ = [
    "AppleDevice",
    "shortcuts_reminder_url",
    "detect_apple",
    "reminder_entry_mode",
    "reminder_landing_html",
    "build_reminder_shortcut",
    "write_reminder_shortcut",
    "reminder_setup_instructions",
    "reminder_setup_html",
]


# --------------------------------------------------------------------------- #
# 1. Shortcuts launch URL
# --------------------------------------------------------------------------- #

def _fmt_due(due: Union[_dt.datetime, _dt.date, str], tz: str) -> str:
    """Serialize a due value to an ISO-8601 string.

    A naive ``datetime`` is localized to ``tz`` first; an aware one is kept as
    is. A bare ``date`` and a pre-formatted ``str`` pass through (a ``str`` is
    trusted to already be ISO-8601).
    """
    if isinstance(due, str):
        return due
    if isinstance(due, _dt.datetime):
        if due.tzinfo is None:
            due = due.replace(tzinfo=ZoneInfo(tz))
        return due.isoformat()
    if isinstance(due, _dt.date):
        return due.isoformat()
    raise TypeError(
        f"due must be datetime, date or str, got {type(due).__name__}"
    )


def shortcuts_reminder_url(
    *,
    name: str,
    title: str,
    due: Optional[Union[_dt.datetime, _dt.date, str]] = None,
    notes: Optional[str] = None,
    url: Optional[str] = None,
    tz: str = "UTC",
    shortcut_input_extra: Optional[Mapping[str, Any]] = None,
) -> str:
    """Build a ``shortcuts://run-shortcut`` URL that adds an Apple Reminder.

    The URL launches the Shortcut named ``name`` and passes a compact JSON
    dictionary as its ``input``. The payload carries a **fixed set of keys**
    the receiving Shortcut is built against:

        title  (str)        -- from ``title``
        due    (str|None)   -- ISO-8601 from ``due`` (see below)
        notes  (str|None)   -- from ``notes``
        url    (str|None)   -- from ``url``

    Any keys in ``shortcut_input_extra`` are merged into the payload (they may
    override the fixed keys if they collide).

    Args:
        name: The exact Shortcut name as installed on the device.
        title: Reminder title.
        due: Optional due date/time. A naive ``datetime`` is localized to
            ``tz`` and serialized with its offset; an aware ``datetime`` keeps
            its own zone; a ``date`` becomes ``YYYY-MM-DD``; a ``str`` is
            passed through unchanged (assumed already ISO-8601).
        notes: Optional notes text.
        url: Optional associated link.
        tz: IANA/zoneinfo name used to localize a naive ``due`` datetime.
        shortcut_input_extra: Optional extra fields merged into the payload.

    Returns:
        A ``shortcuts://run-shortcut?name=<enc>&input=<enc JSON>`` string with
        both ``name`` and the JSON ``input`` fully URL-escaped. The JSON is
        compact (no spaces) and built with ``ensure_ascii=False`` so non-ASCII
        text stays readable before being percent-encoded.
    """
    payload: dict[str, Any] = {
        "title": title,
        "due": _fmt_due(due, tz) if due is not None else None,
        "notes": notes,
        "url": url,
    }
    if shortcut_input_extra:
        payload.update(shortcut_input_extra)

    input_json = _json.dumps(payload, ensure_ascii=False, separators=(",", ":"))

    # safe="" -> escape everything reserved (including / : ? & = and non-ASCII).
    enc_name = quote(name, safe="")
    enc_input = quote(input_json, safe="")
    return f"shortcuts://run-shortcut?name={enc_name}&input={enc_input}"


# --------------------------------------------------------------------------- #
# 2. Apple platform detection
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class AppleDevice:
    """Result of :func:`detect_apple`.

    Attributes:
        is_apple: True if the User-Agent looks like an Apple platform.
        kind: One of ``"iphone"``, ``"ipad"``, ``"ipod"``, ``"mac"``,
            ``"unknown"``.
    """

    is_apple: bool
    kind: str


def detect_apple(user_agent: Optional[str]) -> AppleDevice:
    """Detect whether a User-Agent string is an Apple platform.

    Matching (case-insensitive):
        * ``iPhone``            -> ``iphone``
        * ``iPad``              -> ``ipad``
        * ``iPod``              -> ``ipod``
        * ``Macintosh`` / ``Mac OS X`` (without iPhone/iPad) -> ``mac``
        * anything else / empty / ``None`` -> ``unknown`` (is_apple=False)

    Limitation: **iPadOS Safari can masquerade as ``Macintosh``** (desktop-class
    browsing), so a modern iPad may be reported as ``kind="mac"``. For our
    purposes that is fine: ``is_apple`` is still ``True`` — it is an Apple
    device either way, which is all the Reminders/Shortcuts flow needs.

    Args:
        user_agent: The raw ``User-Agent`` header, or ``None``.

    Returns:
        An :class:`AppleDevice`.
    """
    if not user_agent:
        return AppleDevice(is_apple=False, kind="unknown")

    ua = user_agent.lower()

    # Order matters: real iPod/iPad UAs contain "iPhone OS" (and "Mac OS X"),
    # so check the more specific tokens (ipod, ipad) before iphone/mac.
    if "ipod" in ua:
        return AppleDevice(is_apple=True, kind="ipod")
    if "ipad" in ua:
        return AppleDevice(is_apple=True, kind="ipad")
    if "iphone" in ua:
        return AppleDevice(is_apple=True, kind="iphone")
    if "macintosh" in ua or "mac os x" in ua:
        return AppleDevice(is_apple=True, kind="mac")

    return AppleDevice(is_apple=False, kind="unknown")


def reminder_entry_mode(user_agent: Optional[str]) -> str:
    """Return the reminder entry mode for a User-Agent.

    Args:
        user_agent: The raw ``User-Agent`` header, or ``None``.

    Returns:
        ``"apple"`` if :func:`detect_apple` reports an Apple platform, else
        ``"unknown"`` (also for ``None``/empty).
    """
    return "apple" if detect_apple(user_agent).is_apple else "unknown"


# --------------------------------------------------------------------------- #
# 3. Optional landing-page HTML helper
# --------------------------------------------------------------------------- #

_DEFAULT_LABELS = {
    "ru": {
        "title": "Добавить в Напоминания",
        "button": "📋 Добавить в Напоминания",
        "continue": "Продолжить",
        "warning": (
            "⚠️ Устройство Apple не обнаружено. Эта кнопка сработает, только "
            "если вы сейчас на устройстве Apple (Mac, iPhone или iPad). Если "
            "вы на нём — нажмите «Продолжить». Если нет — откройте эту "
            "страницу с устройства Apple."
        ),
    },
    "en": {
        "title": "Add to Reminders",
        "button": "📋 Add to Reminders",
        "continue": "Continue",
        "warning": (
            "⚠️ Apple device not detected. This button only works if you are "
            "currently on an Apple device (Mac, iPhone or iPad). If you are — "
            "tap “Continue”. If not — open this page from an Apple device."
        ),
    },
}


def reminder_landing_html(
    *,
    shortcut_url: str,
    mode: str,
    lang: str = "ru",
    labels: Optional[Mapping[str, str]] = None,
) -> str:
    """Render a self-contained HTML landing page for the Reminders button.

    This is an **optional convenience helper**. A project is free to render its
    own UI instead, using :func:`reminder_entry_mode` (to pick the state) and
    :func:`shortcuts_reminder_url` (for the link) directly.

    UX by ``mode``:
        * ``"apple"`` — Apple detected. The page shows the action as an
          explicit tool: a prominent **button** linking to ``shortcut_url``.
        * ``"unknown"`` — not detected. The page shows the **same button** as
          an option, plus a warning that it only works on an Apple device and
          the user may continue if they are on one.

    A small inline ``<script>`` re-checks the client's ``navigator`` on load;
    if it detects Apple there (client detection is more accurate than the
    server's User-Agent guess), it flips an ``"unknown"`` page into the
    explicit-tool state — closing the "we didn't detect it but you are on
    Apple" gap.

    Args:
        shortcut_url: The ``shortcuts://`` URL (from
            :func:`shortcuts_reminder_url`) the button opens.
        mode: ``"apple"`` or ``"unknown"`` (typically from
            :func:`reminder_entry_mode`). Any non-``"apple"`` value is treated
            as ``"unknown"``.
        lang: ``"ru"`` (default) or ``"en"`` — picks the default label set.
        labels: Optional overrides for any label keys: ``title``, ``button``,
            ``continue``, ``warning``.

    Returns:
        A complete, minimal, dependency-free HTML document as a string. All
        interpolated values are escaped.
    """
    base = _DEFAULT_LABELS.get(lang, _DEFAULT_LABELS["en"])
    text = dict(base)
    if labels:
        text.update(labels)

    is_apple = mode == "apple"

    # Escape everything that lands in HTML. The shortcut_url goes into an href
    # (quote=True escapes the double-quote that delimits the attribute).
    href = _escape(shortcut_url, quote=True)
    lbl_title = _escape(text["title"])
    lbl_button = _escape(text["button"])
    lbl_continue = _escape(text["continue"])
    lbl_warning = _escape(text["warning"])
    lang_attr = _escape(lang, quote=True)

    # Warning block is present in the DOM but hidden when Apple is detected;
    # the client script can un-hide/re-hide it.
    warning_style = "display:none;" if is_apple else ""
    button_label = lbl_button if is_apple else lbl_continue

    return f"""<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{lbl_title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; padding: 2rem 1rem; background: #f5f5f7; color: #1d1d1f;
         display: flex; justify-content: center; }}
  .card {{ background: #fff; border-radius: 16px; padding: 2rem 1.5rem;
          max-width: 28rem; width: 100%; box-shadow: 0 2px 12px rgba(0,0,0,.08);
          text-align: center; }}
  h1 {{ font-size: 1.25rem; margin: 0 0 1.25rem; }}
  .warning {{ background: #fff8e1; border: 1px solid #ffe082; color: #6d4c00;
             border-radius: 12px; padding: .9rem 1rem; margin: 0 0 1.25rem;
             font-size: .95rem; line-height: 1.4; text-align: left; }}
  .btn {{ display: inline-block; background: #007aff; color: #fff;
         text-decoration: none; font-size: 1.05rem; font-weight: 600;
         padding: .85rem 1.5rem; border-radius: 12px; width: 100%;
         box-sizing: border-box; }}
  .btn:active {{ background: #0062cc; }}
</style>
</head>
<body>
  <div class="card">
    <h1>{lbl_title}</h1>
    <div class="warning" id="reminder-warning" style="{warning_style}">{lbl_warning}</div>
    <a class="btn" id="reminder-btn" href="{href}"
       data-label-tool="{lbl_button}" data-label-continue="{lbl_continue}">{button_label}</a>
  </div>
  <script>
    (function () {{
      var ua = navigator.userAgent || "";
      var plat = navigator.platform || "";
      var s = (ua + " " + plat).toLowerCase();
      var isApple = /iphone|ipad|ipod|macintosh|mac os x|macintel|macppc/.test(s) ||
                    (navigator.maxTouchPoints > 1 && /macintosh|macintel/.test(s));
      if (isApple) {{
        var warn = document.getElementById("reminder-warning");
        var btn = document.getElementById("reminder-btn");
        if (warn) {{ warn.style.display = "none"; }}
        if (btn) {{ btn.textContent = btn.getAttribute("data-label-tool"); }}
      }}
    }})();
  </script>
</body>
</html>"""


# --------------------------------------------------------------------------- #
# 4. First-run: build the unsigned .shortcut file
# --------------------------------------------------------------------------- #
#
# A ``.shortcut`` file is an Apple *property list* describing a Shortcuts
# workflow. The heavy lifting is the ``WFWorkflowActions`` array: an ordered
# list of ``{WFWorkflowActionIdentifier, WFWorkflowActionParameters}`` dicts.
# Actions pass values to each other via magic variables — a producing action
# is tagged with a ``UUID`` parameter, and consumers reference its output with
# an ``ActionOutput`` attachment carrying that ``OutputUUID`` and the action's
# ``OutputName``. We use the documented, stable action identifiers:
#
#   is.workflow.actions.detect.dictionary  -- "Get Dictionary from Input"
#   is.workflow.actions.getvalueforkey     -- "Get Dictionary Value"
#   is.workflow.actions.addnewreminder     -- "Add New Reminder"


def _action(identifier: str, params: dict[str, Any]) -> dict[str, Any]:
    return {
        "WFWorkflowActionIdentifier": identifier,
        "WFWorkflowActionParameters": params,
    }


def _output_attachment(uuid: str, output_name: str) -> dict[str, Any]:
    """A magic-variable reference to a prior action's output."""
    return {
        "OutputUUID": uuid,
        "OutputName": output_name,
        "Type": "ActionOutput",
    }


def _var_token(uuid: str, output_name: str) -> dict[str, Any]:
    """Wrap an output attachment as a standalone tokenized value."""
    return {
        "WFSerializationType": "WFTextTokenAttachment",
        "Value": _output_attachment(uuid, output_name),
    }


def _text_token(pieces: Sequence[tuple[str, str]], *, joiner: str = "") -> dict[str, Any]:
    """Build an interpolated text token from (uuid, output_name) variables.

    Each variable becomes a single object-replacement char (``\\ufffc``) in the
    backing string, joined by ``joiner``; ``attachmentsByRange`` maps each
    ``{offset, 1}`` range to its variable. This is how Shortcuts stores text
    with embedded variables (e.g. ``notes`` + newline + ``url``).
    """
    string_parts: list[str] = []
    attachments: dict[str, Any] = {}
    offset = 0
    for i, (uuid, output_name) in enumerate(pieces):
        if i:
            string_parts.append(joiner)
            offset += len(joiner)
        string_parts.append("￼")
        attachments[f"{{{offset}, 1}}"] = _output_attachment(uuid, output_name)
        offset += 1
    return {
        "WFSerializationType": "WFTextTokenString",
        "Value": {
            "string": "".join(string_parts),
            "attachmentsByRange": attachments,
        },
    }


def _get_value_action(key: str, uuid: str, dict_uuid: str) -> dict[str, Any]:
    return _action(
        "is.workflow.actions.getvalueforkey",
        {
            "UUID": uuid,
            "WFDictionaryKey": key,
            "WFInput": _var_token(dict_uuid, "Dictionary"),
        },
    )


def build_reminder_shortcut(*, name: str = "Add Reminder") -> bytes:
    """Build an **unsigned** Apple ``.shortcut`` file as binary-plist bytes.

    The generated workflow implements the same contract as
    :func:`shortcuts_reminder_url`: it takes text input (the JSON payload),
    parses it into a dictionary, reads the fixed keys ``title`` / ``due`` /
    ``notes`` / ``url``, and adds a Reminder whose notes are ``notes`` + a
    newline + ``url`` and whose due alarm comes from ``due``.

    Action pipeline (documented, stable identifiers):

        1. ``is.workflow.actions.detect.dictionary``  — Get Dictionary from Input
        2. ``is.workflow.actions.getvalueforkey`` × 4 — title / due / notes / url
        3. ``is.workflow.actions.addnewreminder``     — Add New Reminder

    The workflow is stored under the ``WFWorkflowActions`` key and serialized
    with :mod:`plistlib` in ``FMT_BINARY`` (the format Shortcuts expects).

    **Honest Apple limits — do not over-promise.** This file is *not* signed:
    an Apple-signed iCloud share link can only be minted by Apple, never from
    code. Installing an unsigned ``.shortcut`` therefore requires the user to
    enable **"Allow Untrusted Shortcuts"** in Settings and to run the Shortcut
    **once manually** to grant Reminders access. The recommended production
    path is instead a signed iCloud link published once by a human (source
    "icloud" in :func:`reminder_setup_instructions`).

    .. note::
       The action wiring follows Apple's documented identifiers and the
       standard magic-variable serialization, but has **not** been round-trip
       verified on a physical Apple device (no such device in CI). Treat a
       first import on-device as a one-time validation step and adjust the
       alarm/notes parameters there if Apple's runtime expects a variant.

    Args:
        name: Human-visible Shortcut name embedded in the workflow. Must match
            the ``name`` you later pass to :func:`shortcuts_reminder_url`.

    Returns:
        The ``.shortcut`` file contents as binary-plist ``bytes``.
    """
    dict_uuid = str(_uuid4())
    title_uuid = str(_uuid4())
    due_uuid = str(_uuid4())
    notes_uuid = str(_uuid4())
    url_uuid = str(_uuid4())

    actions = [
        # 1. Parse the text input into a dictionary.
        _action("is.workflow.actions.detect.dictionary", {"UUID": dict_uuid}),
        # 2. Pull the fixed keys out of the dictionary.
        _get_value_action("title", title_uuid, dict_uuid),
        _get_value_action("due", due_uuid, dict_uuid),
        _get_value_action("notes", notes_uuid, dict_uuid),
        _get_value_action("url", url_uuid, dict_uuid),
        # 3. Create the Reminder: title, notes = notes + "\n" + url, due alarm.
        _action(
            "is.workflow.actions.addnewreminder",
            {
                "WFReminderTitle": _text_token([(title_uuid, "Dictionary Value")]),
                "WFReminderNotes": _text_token(
                    [
                        (notes_uuid, "Dictionary Value"),
                        (url_uuid, "Dictionary Value"),
                    ],
                    joiner="\n",
                ),
                "WFAlarms": {
                    "Value": {
                        "WFAlarmType": "AlarmFixed",
                        "WFDate": _var_token(due_uuid, "Dictionary Value"),
                    },
                    "WFSerializationType": "WFArrayParameterState",
                },
            },
        ),
    ]

    workflow: dict[str, Any] = {
        "WFWorkflowName": name,
        "WFWorkflowClientVersion": "2607.0.5",
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowMinimumClientVersionString": "900",
        "WFWorkflowIcon": {
            "WFWorkflowIconStartColor": 4292093695,
            "WFWorkflowIconGlyphNumber": 61440,
        },
        "WFWorkflowImportQuestions": [],
        "WFWorkflowTypes": ["NCWidget", "WatchKit"],
        "WFWorkflowInputContentItemClasses": [
            "WFStringContentItem",
            "WFDictionaryContentItem",
        ],
        "WFWorkflowActions": actions,
    }
    return _plistlib.dumps(workflow, fmt=_plistlib.FMT_BINARY)


def write_reminder_shortcut(path: str, *, name: str = "Add Reminder") -> None:
    """Write :func:`build_reminder_shortcut` output to ``path``.

    Args:
        path: Destination file path (``.shortcut`` extension recommended).
        name: Shortcut name (see :func:`build_reminder_shortcut`).
    """
    data = build_reminder_shortcut(name=name)
    with open(_os.fspath(path), "wb") as fh:
        fh.write(data)


# --------------------------------------------------------------------------- #
# 5. First-run: onboarding instructions and setup page
# --------------------------------------------------------------------------- #

_SETUP_STEPS = {
    "ru": {
        "untrusted": [
            "Откройте Настройки → «Быстрые команды» и включите «Разрешать "
            "ненадёжные команды» (Allow Untrusted Shortcuts). Пункт появляется "
            "только после того, как вы хотя бы раз запускали любую команду.",
            "Скачайте файл команды (.shortcut) по кнопке ниже.",
            "Откройте скачанный файл — приложение «Быстрые команды» покажет "
            "действия; пролистайте их и нажмите «Добавить команду».",
            "Запустите команду один раз вручную и разрешите доступ к "
            "Напоминаниям, когда система об этом попросит.",
            "Готово — вернитесь сюда и нажмите «Продолжить».",
        ],
        "icloud": [
            "Нажмите кнопку установки ниже — откроется ссылка iCloud на команду.",
            "В приложении «Быстрые команды» пролистайте действия и нажмите "
            "«Добавить команду».",
            "При первом запуске разрешите доступ к Напоминаниям.",
            "Готово — вернитесь сюда и нажмите «Продолжить».",
        ],
    },
    "en": {
        "untrusted": [
            "Open Settings → Shortcuts and turn on “Allow Untrusted "
            "Shortcuts”. This toggle only appears after you have run at least "
            "one shortcut before.",
            "Download the shortcut file (.shortcut) with the button below.",
            "Open the downloaded file — the Shortcuts app shows its actions; "
            "scroll through them and tap “Add Shortcut”.",
            "Run the shortcut once manually and allow access to Reminders "
            "when the system prompts you.",
            "Done — come back here and tap “Continue”.",
        ],
        "icloud": [
            "Tap the install button below — it opens the iCloud shortcut link.",
            "In the Shortcuts app, scroll through the actions and tap "
            "“Add Shortcut”.",
            "On the first run, allow access to Reminders.",
            "Done — come back here and tap “Continue”.",
        ],
    },
}


def reminder_setup_instructions(
    *, lang: str = "ru", source: str = "untrusted"
) -> list[str]:
    """Return ordered first-run setup steps for installing the Shortcut.

    Args:
        lang: ``"ru"`` (default) or ``"en"``. Unknown values fall back to
            ``"en"``.
        source: Install source — ``"untrusted"`` (the built-in unsigned
            ``.shortcut`` from :func:`build_reminder_shortcut`, which needs
            "Allow Untrusted Shortcuts" + a one-time manual run) or
            ``"icloud"`` (a signed iCloud share link; frictionless).

    Returns:
        A non-empty list of human-readable step strings.

    Raises:
        ValueError: If ``source`` is not ``"untrusted"`` or ``"icloud"``.
    """
    if source not in ("untrusted", "icloud"):
        raise ValueError('source must be "untrusted" or "icloud"')
    steps = _SETUP_STEPS.get(lang, _SETUP_STEPS["en"])
    return list(steps[source])


_DEFAULT_SETUP_LABELS = {
    "ru": {
        "title": "Настройка команды",
        "intro": "Один раз установите команду — дальше напоминания добавляются в одно нажатие.",
        "install": "Установить команду",
        "continue": "Я установил → продолжить",
        "warning": _DEFAULT_LABELS["ru"]["warning"],
    },
    "en": {
        "title": "Set up the Shortcut",
        "intro": "Install the shortcut once — after that, reminders are one tap away.",
        "install": "Install the Shortcut",
        "continue": "I've installed it → continue",
        "warning": _DEFAULT_LABELS["en"]["warning"],
    },
}


def reminder_setup_html(
    *,
    install_url: str,
    source: str = "icloud",
    lang: str = "ru",
    labels: Optional[Mapping[str, str]] = None,
    mode: Optional[str] = None,
) -> str:
    """Render a self-contained first-run **setup** page for the Shortcut.

    The page shows the numbered steps from
    :func:`reminder_setup_instructions` (chosen by ``source``), an **"Install
    the Shortcut"** button pointing at ``install_url`` (either a signed iCloud
    link, or a URL your app serves that streams the bytes from
    :func:`build_reminder_shortcut`), and a secondary **"continue"** button
    for after the user has installed it.

    This helper renders *only* the setup UI. Whether the Shortcut is already
    installed is **state the project owns** — decide that yourself and render
    this setup page vs. the per-task :func:`reminder_landing_html`
    accordingly. The "continue" button is a hook (``id="reminder-continue"``,
    ``href="#"``) the project wires to its own next step.

    Apple detection mirrors :func:`reminder_landing_html`: when
    ``mode="unknown"`` the page shows the **same warning** that a non-Apple
    visitor may be in the wrong place, and an inline ``<script>`` re-checks the
    client's platform (including iPadOS masquerade via ``maxTouchPoints``) and
    hides the warning if Apple is found. Any ``mode`` other than ``"unknown"``
    (including the ``None`` default) renders without the warning.

    Args:
        install_url: URL the install button opens (iCloud link or your own
            ``.shortcut`` download endpoint).
        source: ``"icloud"`` (default) or ``"untrusted"`` — selects which step
            list to render.
        lang: ``"ru"`` (default) or ``"en"``.
        labels: Optional overrides for any of ``title``, ``intro``,
            ``install``, ``continue``, ``warning``.
        mode: ``"unknown"`` to surface the not-Apple warning; anything else
            (or ``None``) renders it hidden.

    Returns:
        A complete, dependency-free HTML document. All interpolated values are
        escaped.
    """
    base = _DEFAULT_SETUP_LABELS.get(lang, _DEFAULT_SETUP_LABELS["en"])
    text = dict(base)
    if labels:
        text.update(labels)

    steps = reminder_setup_instructions(lang=lang, source=source)
    steps_html = "\n".join(f"      <li>{_escape(s)}</li>" for s in steps)

    show_warning = mode == "unknown"
    warning_style = "" if show_warning else "display:none;"

    href = _escape(install_url, quote=True)
    lbl_title = _escape(text["title"])
    lbl_intro = _escape(text["intro"])
    lbl_install = _escape(text["install"])
    lbl_continue = _escape(text["continue"])
    lbl_warning = _escape(text["warning"])
    lang_attr = _escape(lang, quote=True)

    return f"""<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{lbl_title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; padding: 2rem 1rem; background: #f5f5f7; color: #1d1d1f;
         display: flex; justify-content: center; }}
  .card {{ background: #fff; border-radius: 16px; padding: 2rem 1.5rem;
          max-width: 30rem; width: 100%; box-shadow: 0 2px 12px rgba(0,0,0,.08); }}
  h1 {{ font-size: 1.25rem; margin: 0 0 .5rem; text-align: center; }}
  .intro {{ margin: 0 0 1.25rem; color: #555; text-align: center; }}
  .warning {{ background: #fff8e1; border: 1px solid #ffe082; color: #6d4c00;
             border-radius: 12px; padding: .9rem 1rem; margin: 0 0 1.25rem;
             font-size: .95rem; line-height: 1.4; }}
  ol {{ margin: 0 0 1.5rem; padding-left: 1.25rem; line-height: 1.5; }}
  li {{ margin: 0 0 .6rem; }}
  .btn {{ display: block; text-align: center; text-decoration: none;
         font-size: 1.05rem; font-weight: 600; padding: .85rem 1.5rem;
         border-radius: 12px; box-sizing: border-box; margin: 0 0 .75rem; }}
  .btn-install {{ background: #007aff; color: #fff; }}
  .btn-install:active {{ background: #0062cc; }}
  .btn-continue {{ background: #e8e8ed; color: #1d1d1f; }}
  .btn-continue:active {{ background: #d8d8dd; }}
</style>
</head>
<body>
  <div class="card">
    <h1>{lbl_title}</h1>
    <p class="intro">{lbl_intro}</p>
    <div class="warning" id="reminder-warning" style="{warning_style}">{lbl_warning}</div>
    <ol id="reminder-steps">
{steps_html}
    </ol>
    <a class="btn btn-install" id="reminder-install" href="{href}">{lbl_install}</a>
    <a class="btn btn-continue" id="reminder-continue" href="#">{lbl_continue}</a>
  </div>
  <script>
    (function () {{
      var ua = navigator.userAgent || "";
      var plat = navigator.platform || "";
      var s = (ua + " " + plat).toLowerCase();
      var isApple = /iphone|ipad|ipod|macintosh|mac os x|macintel|macppc/.test(s) ||
                    (navigator.maxTouchPoints > 1 && /macintosh|macintel/.test(s));
      if (isApple) {{
        var warn = document.getElementById("reminder-warning");
        if (warn) {{ warn.style.display = "none"; }}
      }}
    }})();
  </script>
</body>
</html>"""
